# Generated by Django 5.2.4 on 2025-08-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='posts',
            new_name='post',
        ),
    ]
